FROM ubuntu
RUN apt-get update && apt-get install -y software-properties-common
RUN apt-get update && add-apt-repository ppa:webupd8team/java
RUN apt-get update && apt-get install -y oracle-java8-installer
RUN apt-get install -y oracle-java8-set-default
RUN java -version
RUN mkdir myservices
COPY target/spring-boot-web-0.0.1-SNAPSHOT.jar myservices/
ENTRYPOINT ["java", "-jar", "myservices/spring-boot-web-0.0.1-SNAPSHOT.jar"]

